plugins {
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.15.0'
group = 'com.barbarajones'
base { archivesName = 'BarbaraJonesMod' }

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', ''
            property 'forge.logging.console.level', 'debug'
            mods { barbarajones { source sourceSets.main } }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', ''
            property 'forge.logging.console.level', 'debug'
            mods { barbarajones { source sourceSets.main } }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [ mod_version: project.version ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([ 'Specification-Title'   : 'barbarajones',
                     'Specification-Vendor'  : 'barbarajones',
                     'Specification-Version' : '1',
                     'Implementation-Title'  : project.name,
                     'Implementation-Version': project.jar.archiveVersion,
                     'Implementation-Vendor' : 'barbarajones' ])
    }
    finalizedBy 'reobfJar'
}
