package com.barbarajones.client.ui;

import com.barbarajones.BarbaraJonesMod;

import com.mojang.blaze3d.systems.RenderSystem;
import net.minecraft.ChatFormatting;
import net.minecraft.Util;
import net.minecraft.client.gui.Font;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.Mth;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * The Krave look, in one place.
 *
 * <p>Every screen and overlay in this mod draws through these helpers so the whole
 * UI reads as one object: a cereal box. Black keyline, a fat red band, a cream
 * hairline, then a dark grape-purple body. Gold for headings, milk-white for the
 * things that matter, chocolate for empty progress tracks.
 *
 * <p>Everything here is pure {@link GuiGraphics} - no external libraries and no
 * hand-rolled vertex formats. The only textures are two tiny atlases generated by
 * {@code tools/make_gui_assets.ps1}; if they were ever missing the panels still
 * draw correctly, because only the corner ornaments and icons come from them.
 *
 * <p>Colour constants are packed ARGB, which is what {@code GuiGraphics.fill} wants.
 */
public final class KraveTheme {

    private KraveTheme() { }

    // ---- palette ------------------------------------------------------------

    /** Panel body, top of the gradient. */
    public static final int PANEL_BODY      = 0xF21C0A22;
    /** Panel body, bottom of the gradient. */
    public static final int PANEL_BODY_LOW  = 0xF20C0312;
    /** The keyline that surrounds everything. */
    public static final int BORDER_OUT      = 0xFF07030A;
    /** Drop shadow ring under panels. */
    public static final int SHADOW          = 0x99000000;

    /** Cereal-box red - the mod's primary accent. */
    public static final int BOX_RED         = 0xFFC81E24;
    public static final int BOX_RED_DARK    = 0xFF7C0F14;
    public static final int BOX_RED_LIGHT   = 0xFFF0574A;

    /** Krave Monster purple - secondary accent, the Kosmos and the boss. */
    public static final int PURPLE          = 0xFF6B3FA0;
    public static final int PURPLE_LIGHT    = 0xFFB07CF0;

    /** Liquid chocolate - empty progress tracks and inset wells. */
    public static final int CHOCOLATE       = 0xFF3A1D0C;
    /** Krave milk - highlights and the brightest text. */
    public static final int MILK            = 0xFFF4EDDD;
    /** Cream hairline inside the red band. */
    public static final int MILK_LINE       = 0x66F4EDDD;

    public static final int GOLD            = 0xFFE9B23C;
    public static final int GRASS           = 0xFF57B03A;
    public static final int DANGER          = 0xFFE23C3C;

    public static final int TEXT            = 0xFFF2E9D8;
    public static final int TEXT_DIM        = 0xFFA2968B;
    public static final int TEXT_LOCKED     = 0xFF5B5262;

    /** Keyboard focus ring. */
    public static final int FOCUS           = 0xFFFFD75E;

    public static final int SCRIM_TOP       = 0xC0140312;
    public static final int SCRIM_BOTTOM    = 0xE8050009;

    // ---- metrics ------------------------------------------------------------

    /** Thickness of the whole cereal-box border: keyline + band + hairline. */
    public static final int BORDER   = 4;
    public static final int PAD      = 8;
    public static final int PAD_S    = 4;
    public static final int PAD_L    = 12;
    /** Height of the title band inside a panel. */
    public static final int TITLE_H  = 20;
    public static final int TAB_H    = 15;
    /** Height of one key/value row. */
    public static final int ROW_H    = 11;
    /** Height of one wrapped text line. */
    public static final int LINE_H   = 9;
    public static final int BAR_H    = 7;

    // ---- textures -----------------------------------------------------------

    /** 4x4 grid of 16px icons. See tools/make_gui_assets.ps1. */
    public static final ResourceLocation ICONS =
            new ResourceLocation(BarbaraJonesMod.MODID, "textures/gui/krave_icons.png");
    /** 2x2 grid of 8px corner ornaments. */
    public static final ResourceLocation FRAME =
            new ResourceLocation(BarbaraJonesMod.MODID, "textures/gui/krave_frame.png");

    private static final int ICON_PX = 16;
    private static final int ICON_ATLAS = 64;
    private static final int FRAME_PX = 8;
    private static final int FRAME_ATLAS = 16;

    public static final int ICON_BOX    = 0;
    public static final int ICON_GRASS  = 1;
    public static final int ICON_CHECK  = 2;
    public static final int ICON_LOCK   = 3;
    public static final int ICON_ARROW  = 4;
    public static final int ICON_SKULL  = 5;
    public static final int ICON_STAR   = 6;
    public static final int ICON_PIBB   = 7;
    public static final int ICON_NUGGET = 8;
    public static final int ICON_DONUT  = 9;
    public static final int ICON_HAT    = 10;
    public static final int ICON_KRAVE  = 11;
    public static final int ICON_FLAME  = 12;
    public static final int ICON_CAR    = 13;
    public static final int ICON_TIE    = 14;
    public static final int ICON_CAT    = 15;

    // ---- colour maths -------------------------------------------------------

    /** Scale the RGB of a packed colour, keeping its alpha. */
    public static int dim(int argb, float f) {
        int a = (argb >>> 24) & 0xFF;
        int r = Mth.clamp((int) (((argb >> 16) & 0xFF) * f), 0, 255);
        int g = Mth.clamp((int) (((argb >> 8) & 0xFF) * f), 0, 255);
        int b = Mth.clamp((int) ((argb & 0xFF) * f), 0, 255);
        return (a << 24) | (r << 16) | (g << 8) | b;
    }

    /** Scale the alpha of a packed colour, keeping its RGB. */
    public static int withAlpha(int argb, float f) {
        int a = Mth.clamp((int) (((argb >>> 24) & 0xFF) * f), 0, 255);
        return (a << 24) | (argb & 0x00FFFFFF);
    }

    public static int lerpColor(int from, int to, float t) {
        t = Mth.clamp(t, 0.0F, 1.0F);
        int a = Mth.lerpInt(t, (from >>> 24) & 0xFF, (to >>> 24) & 0xFF);
        int r = Mth.lerpInt(t, (from >> 16) & 0xFF, (to >> 16) & 0xFF);
        int g = Mth.lerpInt(t, (from >> 8) & 0xFF, (to >> 8) & 0xFF);
        int b = Mth.lerpInt(t, from & 0xFF, to & 0xFF);
        return (a << 24) | (r << 16) | (g << 8) | b;
    }

    /** A slow 0..1 sine off the wall clock, so idle UI never looks frozen. */
    public static float breathe() {
        return (float) ((Math.sin(Util.getMillis() / 420.0D) + 1.0D) * 0.5D);
    }

    // ---- background ---------------------------------------------------------

    /**
     * The full-screen dim our screens sit on, instead of vanilla's dirt/gradient.
     * The scanlines are the mod's VHS motif - the whole thing is meant to look like
     * a tape someone left in the sun.
     */
    public static void scrim(GuiGraphics g, int w, int h) {
        g.fillGradient(0, 0, w, h, SCRIM_TOP, SCRIM_BOTTOM);
        for (int y = 0; y < h; y += 4) {
            g.fill(0, y, w, y + 1, 0x0EFFFFFF);
        }
    }

    // ---- panels -------------------------------------------------------------

    /** The standard cereal-box panel, red band. */
    public static void panel(GuiGraphics g, int x, int y, int w, int h) {
        panel(g, x, y, w, h, BOX_RED);
    }

    /**
     * A cereal-box panel with a chosen band colour. Layers, outside in: drop
     * shadow, black keyline, the coloured band, a cream hairline, then the body.
     */
    public static void panel(GuiGraphics g, int x, int y, int w, int h, int accent) {
        int x2 = x + w;
        int y2 = y + h;
        g.fill(x - 2, y - 2, x2 + 2, y2 + 2, SHADOW);
        g.fill(x, y, x2, y2, BORDER_OUT);
        g.fill(x + 1, y + 1, x2 - 1, y2 - 1, accent);
        // lit along the top edge, shaded along the bottom: a box on a shelf
        g.fill(x + 1, y + 1, x2 - 1, y + 2, dim(accent, 1.35F));
        g.fill(x + 1, y2 - 2, x2 - 1, y2 - 1, dim(accent, 0.55F));
        g.fill(x + 3, y + 3, x2 - 3, y2 - 3, MILK_LINE);
        g.fillGradient(x + BORDER, y + BORDER, x2 - BORDER, y2 - BORDER, PANEL_BODY, PANEL_BODY_LOW);
        cornerOrnaments(g, x, y, w, h);
    }

    /** A shallow inset well - used for scroll viewports and stat blocks. */
    public static void well(GuiGraphics g, int x, int y, int w, int h) {
        g.fill(x, y, x + w, y + h, 0x40000000);
        g.fill(x, y, x + w, y + 1, 0x50000000);
        g.fill(x, y + h - 1, x + w, y + h, 0x18FFFFFF);
    }

    /**
     * The title band at the top of a panel: an icon, the name in caps, and an
     * optional right-aligned counter such as "12/34".
     */
    public static void titleBar(GuiGraphics g, Font f, int x, int y, int w, String title, String right) {
        g.fill(x, y, x + w, y + TITLE_H, 0x50000000);
        g.fill(x, y + TITLE_H - 1, x + w, y + TITLE_H, withAlpha(GOLD, 0.45F));
        icon(g, ICON_BOX, x + 3, y + 2);
        g.drawString(f, ChatFormatting.BOLD + upper(title), x + 22, y + 6, MILK, true);
        if (right != null && !right.isEmpty()) {
            g.drawString(f, right, x + w - PAD_S - f.width(right), y + 6, TEXT_DIM, false);
        }
    }

    /** Gold heading with a rule running out to the right edge. Returns the next y. */
    public static int sectionHeader(GuiGraphics g, Font f, int x, int y, int w, String label) {
        String s = ChatFormatting.BOLD + upper(label);
        g.drawString(f, s, x, y, GOLD, false);
        int lx = x + f.width(s) + PAD_S;
        if (lx < x + w) {
            g.fill(lx, y + 3, x + w, y + 4, withAlpha(GOLD, 0.30F));
        }
        return y + 13;
    }

    /**
     * A "key .... value" row with a dotted leader, so a wide panel still reads
     * left to right. Returns the next y.
     */
    public static int keyValue(GuiGraphics g, Font f, int x, int y, int w,
                               String key, String value, int valueColor) {
        g.drawString(f, key, x, y, TEXT_DIM, false);
        int vw = f.width(value);
        g.drawString(f, value, x + w - vw, y, valueColor, false);
        for (int dx = x + f.width(key) + 3; dx < x + w - vw - 3; dx += 3) {
            g.fill(dx, y + 4, dx + 1, y + 5, 0x33FFFFFF);
        }
        return y + ROW_H;
    }

    public static void divider(GuiGraphics g, int x, int y, int w) {
        g.fill(x, y, x + w, y + 1, 0x28FFFFFF);
        g.fill(x, y + 1, x + w, y + 2, 0x40000000);
    }

    // ---- progress -----------------------------------------------------------

    /** A chocolate-milk progress bar: dark cocoa track, bright fill, milk highlight. */
    public static void progressBar(GuiGraphics g, int x, int y, int w, int h, float frac, int fill) {
        frac = Mth.clamp(frac, 0.0F, 1.0F);
        g.fill(x - 1, y - 1, x + w + 1, y + h + 1, BORDER_OUT);
        g.fill(x, y, x + w, y + h, CHOCOLATE);
        int filled = (int) (w * frac);
        if (filled > 0) {
            g.fill(x, y, x + filled, y + h, fill);
            g.fill(x, y, x + filled, y + Math.max(1, h / 3), withAlpha(MILK, 0.30F));
        }
        // quarter notches, so a glance tells you roughly where you are
        for (int q = 1; q < 4; q++) {
            int nx = x + w * q / 4;
            g.fill(nx, y, nx + 1, y + h, 0x30000000);
        }
    }

    /** Progress bar with a caption drawn centred on top of it. */
    public static void progressBar(GuiGraphics g, Font f, int x, int y, int w, int h,
                                   float frac, int fill, String label) {
        progressBar(g, x, y, w, h, frac, fill);
        if (label != null && !label.isEmpty()) {
            g.drawString(f, label, x + (w - f.width(label)) / 2, y + (h - 7) / 2, MILK, true);
        }
    }

    /** A row of little diamond pips - the compact progress read-out on the HUD. */
    public static void pips(GuiGraphics g, int x, int y, int count, int filled, int lit, int dark) {
        for (int i = 0; i < count; i++) {
            pip(g, x + i * 6, y, i < filled ? lit : dark);
        }
    }

    /** One 5x4 diamond. */
    public static void pip(GuiGraphics g, int x, int y, int color) {
        g.fill(x + 1, y, x + 4, y + 1, color);
        g.fill(x, y + 1, x + 5, y + 3, color);
        g.fill(x + 1, y + 3, x + 4, y + 4, color);
    }

    // ---- tabs ---------------------------------------------------------------

    public static int tabWidth(int w, int count) {
        return count <= 0 ? 0 : (w - (count - 1) * 2) / count;
    }

    public static int tabX(int x, int w, int count, int index) {
        return x + index * (tabWidth(w, count) + 2);
    }

    /** Hit-test for {@link #tabStrip}; returns the tab index under the point, or -1. */
    public static int tabAt(int x, int y, int w, int count, double mouseX, double mouseY) {
        if (count <= 0 || mouseY < y || mouseY >= y + TAB_H) {
            return -1;
        }
        int tw = tabWidth(w, count);
        for (int i = 0; i < count; i++) {
            int tx = tabX(x, w, count, i);
            if (mouseX >= tx && mouseX < tx + tw) {
                return i;
            }
        }
        return -1;
    }

    /**
     * Draws the tab strip. The selected tab shares the panel body colour so it
     * reads as continuous with the content underneath it. Returns the hovered index.
     */
    public static int tabStrip(GuiGraphics g, Font f, int x, int y, int w,
                               List<String> labels, int selected, int mouseX, int mouseY) {
        int n = labels.size();
        if (n == 0) {
            return -1;
        }
        int tw = tabWidth(w, n);
        int hovered = tabAt(x, y, w, n, mouseX, mouseY);
        for (int i = 0; i < n; i++) {
            int tx = tabX(x, w, n, i);
            boolean sel = i == selected;
            boolean hot = i == hovered;
            g.fill(tx, y, tx + tw, y + TAB_H, sel ? PANEL_BODY : (hot ? 0xFF2C1434 : 0xFF160718));
            g.fill(tx, y, tx + tw, y + 2, sel ? BOX_RED : (hot ? BOX_RED_DARK : 0xFF3A1520));
            if (!sel) {
                g.fill(tx, y + TAB_H - 1, tx + tw, y + TAB_H, 0x60000000);
            }
            String label = trimTo(f, upper(labels.get(i)), tw - 6);
            g.drawString(f, (sel ? ChatFormatting.BOLD.toString() : "") + label,
                    tx + (tw - f.width(label)) / 2, y + 5, sel ? MILK : TEXT_DIM, false);
        }
        return hovered;
    }

    // ---- scrolling ----------------------------------------------------------

    /** Vertical scrollbar for a scissored viewport. Draws nothing if it all fits. */
    public static void scrollbar(GuiGraphics g, int x, int y, int h, int contentH, int viewH, int scroll) {
        if (contentH <= viewH || h <= 0) {
            return;
        }
        g.fill(x, y, x + 3, y + h, 0x60000000);
        int max = contentH - viewH;
        int thumb = Math.max(12, h * viewH / contentH);
        int ty = y + (h - thumb) * Mth.clamp(scroll, 0, max) / Math.max(1, max);
        g.fill(x, ty, x + 3, ty + thumb, BOX_RED);
        g.fill(x, ty, x + 1, ty + thumb, BOX_RED_LIGHT);
    }

    // ---- focus --------------------------------------------------------------

    /**
     * The keyboard focus ring: marching gold dashes. Deliberately loud - if you are
     * driving this UI from the keyboard you should never have to hunt for the caret.
     */
    public static void focusRing(GuiGraphics g, int x, int y, int w, int h) {
        int phase = (int) ((Util.getMillis() / 70L) % 4L);
        for (int dx = 0; dx < w; dx++) {
            if (((dx + phase) & 3) < 2) {
                g.fill(x + dx, y - 1, x + dx + 1, y, FOCUS);
                g.fill(x + dx, y + h, x + dx + 1, y + h + 1, FOCUS);
            }
        }
        for (int dy = 0; dy < h; dy++) {
            if (((dy + phase) & 3) < 2) {
                g.fill(x - 1, y + dy, x, y + dy + 1, FOCUS);
                g.fill(x + w, y + dy, x + w + 1, y + dy + 1, FOCUS);
            }
        }
    }

    // ---- icons --------------------------------------------------------------

    public static void icon(GuiGraphics g, int index, int x, int y) {
        icon(g, index, x, y, 1.0F);
    }

    public static void icon(GuiGraphics g, int index, int x, int y, float alpha) {
        int u = (index % 4) * ICON_PX;
        int v = (index / 4) * ICON_PX;
        RenderSystem.enableBlend();
        g.setColor(1.0F, 1.0F, 1.0F, Mth.clamp(alpha, 0.0F, 1.0F));
        g.blit(ICONS, x, y, 0, (float) u, (float) v, ICON_PX, ICON_PX, ICON_ATLAS, ICON_ATLAS);
        g.setColor(1.0F, 1.0F, 1.0F, 1.0F);
        RenderSystem.disableBlend();
    }

    /** The four little bracket flourishes that sit on a panel's corners. */
    public static void cornerOrnaments(GuiGraphics g, int x, int y, int w, int h) {
        if (w < FRAME_PX * 2 || h < FRAME_PX * 2) {
            return;
        }
        RenderSystem.enableBlend();
        g.blit(FRAME, x, y, 0, 0.0F, 0.0F, FRAME_PX, FRAME_PX, FRAME_ATLAS, FRAME_ATLAS);
        g.blit(FRAME, x + w - FRAME_PX, y, 0, (float) FRAME_PX, 0.0F,
                FRAME_PX, FRAME_PX, FRAME_ATLAS, FRAME_ATLAS);
        g.blit(FRAME, x, y + h - FRAME_PX, 0, 0.0F, (float) FRAME_PX,
                FRAME_PX, FRAME_PX, FRAME_ATLAS, FRAME_ATLAS);
        g.blit(FRAME, x + w - FRAME_PX, y + h - FRAME_PX, 0, (float) FRAME_PX, (float) FRAME_PX,
                FRAME_PX, FRAME_PX, FRAME_ATLAS, FRAME_ATLAS);
        RenderSystem.disableBlend();
    }

    // ---- text ---------------------------------------------------------------

    /** Draws wrapped plain text and returns the y below it. */
    public static int textBlock(GuiGraphics g, Font f, int x, int y, int w, String text, int color) {
        for (String line : wrap(f, text, w, 0)) {
            g.drawString(f, line, x, y, color, false);
            y += LINE_H;
        }
        return y;
    }

    /**
     * Greedy word wrap on a plain string. {@code maxLines <= 0} means unlimited;
     * otherwise the last kept line gets an ellipsis when text was dropped.
     *
     * <p>Hand-rolled rather than {@code Font.split} because the HUD has to be able
     * to show that it truncated - a silently cut objective is worse than none.
     */
    public static List<String> wrap(Font f, String text, int width, int maxLines) {
        List<String> all = new ArrayList<>();
        if (text == null || text.isEmpty() || width <= 0) {
            return all;
        }
        StringBuilder line = new StringBuilder();
        for (String word : text.split("\\s+")) {
            if (word.isEmpty()) {
                continue;
            }
            String probe = line.length() == 0 ? word : line + " " + word;
            // a single word wider than the column still has to go somewhere
            if (line.length() == 0 || f.width(probe) <= width) {
                line.setLength(0);
                line.append(probe);
            } else {
                all.add(line.toString());
                line.setLength(0);
                line.append(word);
            }
        }
        if (line.length() > 0) {
            all.add(line.toString());
        }
        if (maxLines <= 0 || all.size() <= maxLines) {
            return all;
        }
        List<String> cut = new ArrayList<>(all.subList(0, maxLines));
        String last = cut.get(maxLines - 1);
        while (last.length() > 1 && f.width(last + "...") > width) {
            last = last.substring(0, last.length() - 1);
        }
        cut.set(maxLines - 1, last + "...");
        return cut;
    }

    /** Cuts a string down until it fits, adding an ellipsis if anything was lost. */
    public static String trimTo(Font f, String text, int width) {
        if (text == null || text.isEmpty() || f.width(text) <= width) {
            return text == null ? "" : text;
        }
        String cut = text;
        while (cut.length() > 1 && f.width(cut + "...") > width) {
            cut = cut.substring(0, cut.length() - 1);
        }
        return cut + "...";
    }

    private static String upper(String s) {
        return s == null ? "" : s.toUpperCase(Locale.ROOT);
    }
}
